pod 'JSONKit', '~> 1.5pre'
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'AFNetworking', '~> 2.3.1'
pod 'SDWebImage', '~> 3.7.1'
pod 'MMDrawerController', '~> 0.5.6'
pod 'UMeng', '~> 2.2.1'
pod 'UMengFeedback', '~> 1.4.1'

pod 'WeChatSDK', '~> 0.0.1'
